---
title: "Day 3 Exercise"
author: "Eileen"
date: "9/19/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source(here::here("data/day3_objects.R"))
```

```{r}
ggplot(data = gapminder07) + geom_point(aes(x = gdpPercap, y = lifeExp)) + 
  labs(title = "Relatioship between life expectancy and GDP per capita in 2007",
       x = "GDP per capita", y = "Life Expectation")
```

```{r}
ggplot(data = gapminder07) + geom_point(aes(x = log(pop), y = log(gdpPercap))) + 
  labs(title = "Relationship between population and GDP per capita",
       x = "Natural log of Population", y = "Natural log of GDP per capita")
```

```{r}
generation$sum_hydro = generation$large_hydro+generation$small_hydro
ggplot(data = generation) + geom_col(aes(x = datetime, y = sum_hydro)) + 
  labs(title = "Hydro Power Generated over time")
  
```

```{r}
long_merged_energy %>%
  group_by(source) %>% 
  summarise(output=sum(output)) %>%
  ggplot() + 
  geom_col(aes(x = source, y = output), fill = "darkred") + 
  geom_hline(aes(yintercept = mean(output))) +
  labs(title = "Amount of energy generated by each source")
```

```{r}
long_gen %>%
  filter(source=="wind"|source=="solar"|source=="geothermal") %>% 
  ggplot() +
  geom_line(aes(x = datetime, y = output, group = source, col = source))
```

```{r}
long_merged_energy %>%
  mutate(date = lubridate::hour(datetime)) %>%
  group_by(date, source) %>%
  summarize(output = sum(output)) %>%
  ggplot() +
  geom_col(aes(x = date, y = output, group = source, fill = source)) +
  scale_fill_brewer(palette = "Set3") + 
  labs(title = "Average hourly output by source", x = "Time", y = "Output")
```

```{r}
long_gen %>%
  rename(type = source) %>%
  merge(regroup, by = "type") %>%
  ggplot() + 
  geom_line(aes(x = datetime, y = output, group = group, col = group)) + 
  facet_wrap(~type, scales = "free") +
  labs(title = "Generate patterns for difference souces")
  
```